import http from 'node:http';
import { readFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadEnvFile } from 'node:process';
import { openDatabase,bindSource,publicJobs,runSync,syncStatus,SafeError } from './lib/core.mjs';
import { createGoogleReader } from './lib/google.mjs';

export const ROOT=path.dirname(fileURLToPath(import.meta.url));
export function loadEnvironment(){const file=path.join(ROOT,'.env');if(existsSync(file))loadEnvFile(file)}
export function databasePath(){return path.resolve(ROOT,process.env.DATABASE_PATH||'data/shortlist.sqlite')}
export function configuredReader(db){const id=process.env.GOOGLE_SPREADSHEET_ID;if(id)bindSource(db,id+'\n'+(process.env.GOOGLE_SHEET_TAB||'Jobs'));return createGoogleReader()}
function headers(type){return {'Content-Type':type,'X-Content-Type-Options':'nosniff','Referrer-Policy':'strict-origin-when-cross-origin','Content-Security-Policy':"default-src 'self'; script-src 'self' https://www.googletagmanager.com; style-src 'self'; img-src 'self'; connect-src 'self' https://www.google-analytics.com https://region1.google-analytics.com; object-src 'none'; base-uri 'none'; frame-ancestors 'none'; form-action 'none'",'Permissions-Policy':'camera=(), microphone=(), geolocation=()'}}
const htmlEscape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const descriptionText=value=>String(value??'').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/<[^>]*>/g,' ').replace(/&amp;/g,'&').replace(/\s+/g,' ').trim();
function jobPage(job,base){const description=descriptionText(job.description);const canonical=`${base}/jobs/${encodeURIComponent(job.job_id)}`;const schema={"@context":"https://schema.org","@type":"JobPosting",title:job.title,description,datePosted:job.posted_at||undefined,hiringOrganization:{"@type":"Organization",name:job.company},url:canonical,directApply:false};if(job.location)schema.jobLocation={"@type":"Place",address:{"@type":"PostalAddress",addressLocality:job.location}};return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${htmlEscape(job.title)} — ${htmlEscape(job.company)} | Shortlist</title><meta name="description" content="${htmlEscape(`${job.title} at ${job.company}. ${job.location||'See eligibility and application details.'}`)}"><link rel="canonical" href="${htmlEscape(canonical)}"><script type="application/ld+json">${JSON.stringify(schema).replace(/</g,'\\u003c')}</script><link rel="stylesheet" href="/styles.css"></head><body><main class="wrap seo-job"><p><a href="/">← Back to Shortlist</a></p><p class="eyebrow">${htmlEscape(job.company)}</p><h1>${htmlEscape(job.title)}</h1><p class="seo-meta">${htmlEscape(job.location||'Location not specified')} · ${htmlEscape(job.work_arrangement||'Work arrangement not specified')}</p><h2>About the role</h2><p>${htmlEscape(description)}</p><p><a class="apply-link" href="${htmlEscape(job.application_url)}" rel="nofollow noopener noreferrer">Apply on the original site ↗</a></p><p class="privacy-note">Shortlist links to the original employer listing. Confirm details and eligibility before applying.</p></main></body></html>`}
function sitemapXml(jobs,base){return `<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><url><loc>${htmlEscape(base)}/</loc></url>${jobs.map(j=>`<url><loc>${htmlEscape(`${base}/jobs/${encodeURIComponent(j.job_id)}`)}</loc>${j.posted_at?`<lastmod>${htmlEscape(j.posted_at)}</lastmod>`:''}</url>`).join('')}</urlset>`}
export function createAppServer(db){const assets=new Map([['/',['index.html','text/html; charset=utf-8']],['/index.html',['index.html','text/html; charset=utf-8']],['/app.js',['app.js','text/javascript; charset=utf-8']],['/styles.css',['styles.css','text/css; charset=utf-8']]]);return http.createServer(async(req,res)=>{try{const requestUrl=new URL(req.url,'http://localhost');const pathname=requestUrl.pathname;const json=(status,data)=>{res.writeHead(status,{...headers('application/json; charset=utf-8'),'Cache-Control':'no-store'});res.end(req.method==='HEAD'?undefined:JSON.stringify(data))};if(!['GET','HEAD'].includes(req.method)){json(405,{error:'Method not allowed'});return}if(pathname==='/api/jobs'){const status=syncStatus(db);if(!status.lastSuccess){json(503,{error:'Jobs are not available yet. Please try again later.'});return}json(200,{jobs:publicJobs(db),lastUpdated:status.lastSuccess});return}const jobs=publicJobs(db);const base=process.env.PUBLIC_BASE_URL||`${requestUrl.protocol}//${requestUrl.host}`;if(pathname==='/sitemap.xml'){const limit=Math.max(1,Number(process.env.SEO_JOB_LIMIT||5));const content=sitemapXml(jobs.slice(0,limit),base);res.writeHead(200,{...headers('application/xml; charset=utf-8'),'Cache-Control':'no-cache'});res.end(req.method==='HEAD'?undefined:content);return}if(pathname==='/robots.txt'){const content=`User-agent: *\nAllow: /\nSitemap: ${base}/sitemap.xml\n`;res.writeHead(200,{...headers('text/plain; charset=utf-8'),'Cache-Control':'no-cache'});res.end(req.method==='HEAD'?undefined:content);return}if(pathname.startsWith('/jobs/')){const id=decodeURIComponent(pathname.slice('/jobs/'.length));const job=jobs.find(item=>item.job_id===id);if(!job){res.writeHead(404,headers('text/plain; charset=utf-8'));res.end('Job not found');return}const content=jobPage(job,base);res.writeHead(200,{...headers('text/html; charset=utf-8'),'Cache-Control':'no-cache'});res.end(req.method==='HEAD'?undefined:content);return}const asset=assets.get(pathname);if(asset){const content=await readFile(path.join(ROOT,'public',asset[0]));res.writeHead(200,{...headers(asset[1]),'Cache-Control':'no-cache'});res.end(req.method==='HEAD'?undefined:content);return}if(pathname==='/favicon.ico'){res.writeHead(204);res.end();return}json(404,{error:'Not found'})}catch{if(!res.headersSent){res.writeHead(500,headers('application/json; charset=utf-8'));res.end('{"error":"Service temporarily unavailable"}')}else res.end()}})}
export async function main(){loadEnvironment();const db=openDatabase(databasePath());let fetchValues;try{fetchValues=configuredReader(db)}catch(e){db.close();throw e}const server=createAppServer(db);const port=Number(process.env.PORT||3000),host=process.env.HOST||'127.0.0.1';if(!Number.isInteger(port)||port<1||port>65535)throw new SafeError('INVALID_PORT');let active=null,stopping=false;const tick=()=>{if(stopping||active)return;active=runSync(db,fetchValues).then(result=>{if(!result.skipped){const {issues,...safeSummary}=result;console.log(JSON.stringify({event:'sheet_sync',...safeSummary}))}}).catch(()=>console.error(JSON.stringify({event:'sheet_sync',errorCode:'DATABASE_ERROR'}))).finally(()=>{active=null})};server.listen(port,host,()=>{console.log('Shortlist listening on '+host+':'+port);tick()});const timer=setInterval(tick,15000);timer.unref();const stop=()=>{if(stopping)return;stopping=true;clearInterval(timer);server.close(async()=>{if(active)await active;db.close();process.exit(0)})};process.on('SIGINT',stop);process.on('SIGTERM',stop);server.on('error',()=>{console.error('Server could not start; check HOST and PORT.');clearInterval(timer);db.close();process.exitCode=1})}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url))main().catch(e=>{console.error(e instanceof SafeError?e.code:'STARTUP_FAILED');process.exitCode=1});
