import { readFile } from 'node:fs/promises';
import { createSign } from 'node:crypto';
import { SafeError } from './core.mjs';
const endpoint=(host,pathname)=>['https:','',host,pathname].join('/');
const TOKEN_URL=endpoint('oauth2.googleapis.com','token');
const SCOPE=endpoint('www.googleapis.com','auth/spreadsheets.readonly');
export async function responseJson(response,{code='UPSTREAM_ERROR',maxBytes=20*1024*1024}={}){if(!response.ok){await response.body?.cancel();throw new SafeError(code+'_HTTP_'+response.status)}if(Number(response.headers.get('content-length'))>maxBytes)throw new SafeError('RESPONSE_TOO_LARGE');const reader=response.body.getReader();let count=0;const chunks=[];try{for(;;){const {done,value}=await reader.read();if(done)break;count+=value.byteLength;if(count>maxBytes)throw new SafeError('RESPONSE_TOO_LARGE');chunks.push(Buffer.from(value))}}finally{await reader.cancel().catch(()=>{})}try{return JSON.parse(Buffer.concat(chunks).toString('utf8'))}catch{throw new SafeError(code+'_INVALID_JSON')}}
async function readCredentials(env){if(env.GOOGLE_APPLICATION_CREDENTIALS){try{const d=JSON.parse(await readFile(env.GOOGLE_APPLICATION_CREDENTIALS,'utf8'));if(d.type!=='service_account')throw Error();return d}catch{throw new SafeError('CREDENTIAL_FILE_INVALID')}}return {client_email:env.GOOGLE_SERVICE_ACCOUNT_EMAIL,private_key:env.GOOGLE_PRIVATE_KEY?.replace(/\\n/g,'\n')}}
export function createGoogleReader(env=process.env,{fetchImpl=fetch}={}){let token,expires=0;
 async function accessToken(){if(token&&Date.now()<expires)return token;const creds=await readCredentials(env);if(!creds.client_email||!creds.private_key)throw new SafeError('GOOGLE_CREDENTIALS_NOT_CONFIGURED');const now=Math.floor(Date.now()/1000);const b64=x=>Buffer.from(JSON.stringify(x)).toString('base64url');const unsigned=b64({alg:'RS256',typ:'JWT'})+'.'+b64({iss:creds.client_email,scope:SCOPE,aud:TOKEN_URL,iat:now,exp:now+3600});let signature;try{signature=createSign('RSA-SHA256').update(unsigned).end().sign(creds.private_key,'base64url')}catch{throw new SafeError('PRIVATE_KEY_INVALID')}
 const body=new URLSearchParams({grant_type:'urn:ietf:params:oauth:grant-type:jwt-bearer',assertion:unsigned+'.'+signature});let r;try{r=await fetchImpl(TOKEN_URL,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body,redirect:'error',signal:AbortSignal.timeout(20000)})}catch{throw new SafeError('GOOGLE_AUTH_UNREACHABLE')}
 const d=await responseJson(r,{code:'GOOGLE_AUTH',maxBytes:100000});if(typeof d.access_token!=='string'||!Number.isFinite(Number(d.expires_in)))throw new SafeError('GOOGLE_TOKEN_INVALID');token=d.access_token;expires=Date.now()+Math.max(0,Number(d.expires_in)-90)*1000;return token;
 }
 return async function readSheet(){const id=env.GOOGLE_SPREADSHEET_ID,tab=env.GOOGLE_SHEET_TAB||'Jobs';if(!id||!/^[-_A-Za-z0-9]+$/.test(id))throw new SafeError('SPREADSHEET_ID_NOT_CONFIGURED');if(tab.length>100||/[\u0000-\u001f]/.test(tab))throw new SafeError('SHEET_TAB_INVALID');const range="'"+tab.replaceAll("'","''")+"'!A:M";const u=new URL(endpoint('sheets.googleapis.com','v4/spreadsheets/')+encodeURIComponent(id)+'/values/'+encodeURIComponent(range));u.searchParams.set('majorDimension','ROWS');u.searchParams.set('valueRenderOption','FORMULA');const t=await accessToken();let r;try{r=await fetchImpl(u,{headers:{Authorization:'Bearer '+t,Accept:'application/json'},redirect:'error',signal:AbortSignal.timeout(25000)})}catch{throw new SafeError('GOOGLE_SHEETS_UNREACHABLE')}if(r.status===401){token=null;expires=0}const d=await responseJson(r,{code:'GOOGLE_SHEETS'});if(!Array.isArray(d.values))throw new SafeError('SHEET_HEADER_MISSING');return d.values;
 }
}
